version: '3'

services:
   cassandra-1:
     image: cassandra
     restart: always
     ports:
       - 9042:9042

   cassandra-2:
     depends_on:
       - cassandra-1
     image: cassandra
     restart: always
     ports:
       - 9043:9042
     environment:
       - "CASSANDRA_SEEDS=cassandra-1"
