version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_container
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cassandra_cluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
    ports:
      - "7000:7000"  # Comunicación entre nodos
      - "7001:7001"  # Comunicación interna segura
      - "9042:9042"  # Cliente CQL
      - "9043:9043"  # Cliente CQL seguro
      - "9191:9191"  # Puerto de autenticación
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_network

networks:
  cassandra_network:
    driver: bridge

volumes:
  cassandra_data:
